# Generated by Django 2.1.5 on 2019-08-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_entry', '0004_auto_20190807_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='predict',
            name='password',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='predict',
            name='username',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
