# Generated by Django 2.1.5 on 2019-08-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_entry', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
