# Generated by Django 2.1.5 on 2019-08-10 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict_entry', '0007_auto_20190808_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predict',
            name='password',
        ),
        migrations.RemoveField(
            model_name='predict',
            name='username',
        ),
    ]
