# Generated by Django 2.1.5 on 2019-08-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_entry', '0008_auto_20190810_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='predict',
            name='email',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
