# Generated by Django 2.1.5 on 2019-08-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_entry', '0009_predict_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='predict',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='predict',
            name='image',
            field=models.FileField(blank=True, upload_to='inputimage'),
        ),
    ]
