# Generated by Django 2.1.5 on 2019-08-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_entry', '0010_auto_20190812_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='churn',
            name='contract',
            field=models.CharField(choices=[('One year', 'One year'), ('Month-to-month', 'Month-to-month'), ('Two year', 'Two year')], default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='churn',
            name='internet_service',
            field=models.CharField(choices=[('DSL', 'DSL'), ('Fiber optic', 'Fiber optic'), ('No', 'No')], default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='churn',
            name='payment',
            field=models.CharField(choices=[('Bank transfer (automatic)', 'Bank transfer (automatic)'), ('Credit card (automatic)', 'Credit card (automatic)'), ('Electronic check', 'Electronic check'), ('Mailed check', 'Mailed check')], default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='nonchurn',
            name='noncontract',
            field=models.CharField(choices=[('One year', 'One year'), ('Month-to-month', 'Month-to-month'), ('Two year', 'Two year')], default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='nonchurn',
            name='noninternet_service',
            field=models.CharField(choices=[('DSL', 'DSL'), ('Fiber optic', 'Fiber optic'), ('No', 'No')], default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='nonchurn',
            name='nonpayment',
            field=models.CharField(choices=[('Bank transfer (automatic)', 'Bank transfer (automatic)'), ('Credit card (automatic)', 'Credit card (automatic)'), ('Electronic check', 'Electronic check'), ('Mailed check', 'Mailed check')], default=1, max_length=50),
        ),
    ]
